- name: install the NewRelic repo from a remote rpm
  sudo: true
  yum: name=http://download.newrelic.com/pub/newrelic/el5/i386/newrelic-repo-5-3.noarch.rpm state=present

- name: install package
  sudo: true
  yum: pkg=newrelic-sysmond state=installed
  notify: restart newrelic-sysmond

- name: generate config
  sudo: true
  template: >
    src=nrsysmond.cfg.j2
    dest=/etc/newrelic/nrsysmond.cfg
    owner=root
    group=newrelic
    mode=0640
  notify: restart newrelic-sysmond
